services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - PASSWORD_FILE_PATH=/run/secrets/db-password-prod
      - DB_HOST=db
      - DB_NAME=photo-gallery
      - DB_USER=admin

  db:
    volumes:
      - db-data-prod:/var/lib/mysql
    secrets:
      - db-password-prod
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password-prod
      - MARIADB_DATABASE=photo-gallery
    ports: []

volumes:
  db-data-prod:

secrets:
  db-password-prod:
    environment: "DB_PASSWORD_PROD"
