services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    ports:
      - 9000:80
    entrypoint: ["/var/www/html/docker/entrypoint-prod.sh"]
    command: ["apache2-foreground"]
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - anthropic-api-key
      - db-password-prod
    environment:
      - DB_PASSWORD_PROD_FILE=/run/secrets/db-password-prod
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic-api-key

  db:
    volumes:
      - db-data-prod:/var/lib/mysql
    secrets:
      - db-password-prod
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password-prod
      - MARIADB_DATABASE=photo-gallery
    ports: []

volumes:
  db-data-prod:

secrets:
  db-password-prod:
    file: secrets/db-password-prod.txt
  anthropic-api-key:
    file: secrets/anthropic-api-key.txt
