App\Application\Commands\Photograph\CreateCommand:
    constraints:
        - App\Infrastructure\Symfony\Validator\Photograph\CreateCommandConstraint:
            message: 'Title is already in use.'
    properties:
        title:
            - NotBlank: ~

App\Application\Query\Photograph\GenerateDescriptionForKnownPhotographUuidQuery:
    constraints:
        - App\Infrastructure\Symfony\Validator\Photograph\GenerateDescriptionForKnownPhotographUuidConstraint:
            message: 'Uuid is not known.'
    properties:
        uuid:
            - NotBlank: ~
