services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $publicImageDir: '%public_images_dir%'

    App\Fixtures\:
        resource: '../fixtures/*'

    App\Application\Handler\Photograph\GenerateDescriptionHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $imageDescriptionGenerator: '@App\Infrastructure\Anthropic\Client\ImageDescriptionGeneratorCustom'
