<?php

declare(strict_types=1);

namespace App\Tests\Integration\Infrastructure\Doctrine\Repository;

use App\Domain\Entity\Photograph;
use App\Domain\ValueObject\CreatedAt;
use App\Domain\ValueObject\Description;
use App\Domain\ValueObject\FilePath;
use App\Domain\ValueObject\Title;
use App\Domain\ValueObject\UpdatedAt;
use App\Domain\ValueObject\UUID;
use App\Infrastructure\Doctrine\Repository\PhotographRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Exception;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\DBAL\Platforms\SqlitePlatform;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class PhotographRepositoryTest extends KernelTestCase
{
    private PhotographRepository $photographRepository;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp();
        self::bootKernel();

        $container = static::getContainer();

        $this->photographRepository = $container->get(PhotographRepository::class);

        if ($this->isUsingSqlite()) {
            $this->createSqliteSchema();
        }
    }

    #[Test]
    public function canSavePhotographWithUUID(): void
    {
        $uuid = new UUID('61b2f603-b53a-400e-828f-1725c39d97bf');
        $title = new Title('Title of canSavePhotographWithUUID');
        $description = new Description('Description of canSavePhotographWithUUID');
        $filePath = new FilePath('/public/images/image.jpg');
        $createdAt = new CreatedAt(new DateTimeImmutable('2025-10-04 08:30:00'));
        $updatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 09:30:00'));

        $photograph = new Photograph(
            uuid: $uuid,
            title: $title,
            description: $description,
            filePath: $filePath,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );

        $this->photographRepository->save($photograph);

        self::assertInstanceOf(UUID::class, $photograph->uuid());
        self::assertSame($uuid, $photograph->uuid());
        self::assertSame($title, $photograph->title());
        self::assertSame($description, $photograph->description());
        self::assertSame($filePath, $photograph->filePath());
        self::assertSame($createdAt, $photograph->createdAt());
        self::assertSame($updatedAt, $photograph->updatedAt());
    }

    #[Test]
    public function canSavePhotographWithAutogeneratedUUID(): void
    {
        $title = new Title('Title of canSavePhotographWithAutogeneratedUUID');
        $description = new Description('Description of canSavePhotographWithAutogeneratedUUID');
        $filePath = new FilePath('/public/images/image.jpg');
        $createdAt = new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00'));
        $updatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00'));

        $photograph = new Photograph(
            uuid: null,
            title: $title,
            description: $description,
            filePath: $filePath,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );

        $this->photographRepository->save($photograph);

        self::assertInstanceOf(UUID::class, $photograph->uuid());
        self::assertHasValidUUID($photograph->uuid()->__toString());
        self::assertSame($title, $photograph->title());
        self::assertSame($description, $photograph->description());
        self::assertSame($filePath, $photograph->filePath());
        self::assertSame($createdAt, $photograph->createdAt());
        self::assertSame($updatedAt, $photograph->updatedAt());
    }

    #[Test]
    public function triggersUniqueConstraintViolationExceptionWhenCreatingPhotographWithNotUniqueTitle(): void
    {
        $this->expectException(UniqueConstraintViolationException::class);

        $title = new Title('Title of doesNotAllowCreatingPhotographWhenTitleIsNotUnique');

        $photograph = new Photograph(
            uuid: new UUID('393152da-e0d4-4f27-8111-5d3f5ff6d840'),
            title: $title,
            description: new Description('Description of doesNotAllowCreatingPhotographWhenTitleIsNotUnique'),
            filePath: new FilePath('/public/images/image.jpg'),
            createdAt: new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00')),
            updatedAt: new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00')),
        );

        $this->photographRepository->save($photograph);

        $photograph = new Photograph(
            uuid: new UUID('110a9f66-272c-4f20-9b43-3b0686e0661f'),
            title: $title,
            description: new Description('Description of doesNotAllowCreatingPhotographWhenTitleIsNotUnique'),
            filePath: new FilePath('/public/images/image.jpg'),
            createdAt: new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00')),
            updatedAt: new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00')),
        );

        $this->photographRepository->save($photograph);
    }

    #[Test]
    public function updatesPhotographWhenSavingPhotographWithSameUUID(): void
    {
        $uuid = new UUID('379c3f9a-2c3d-4ede-b7b6-28f9c4ee4991');

        $title = new Title('Title');
        $description = new Description('Description');
        $filePath = new FilePath('/public/images/imageA.jpg');
        $createdAt = new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00'));
        $updatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00'));

        $photograph1 = new Photograph(
            uuid: $uuid,
            title: $title,
            description: $description,
            filePath: $filePath,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );

        $this->photographRepository->save($photograph1);

        $updatedTitle = new Title('Updated Title from updatesWhenSavingPhotographWithExistingUUID');
        $updatedDescription = new Description('Updated Description from updatesWhenSavingPhotographWithExistingUUID');
        $updatedFilePath = new FilePath('/public/images/imageB.jpg');

        $photograph2 = new Photograph(
            uuid: $uuid,
            title: $updatedTitle,
            description: $updatedDescription,
            filePath: $updatedFilePath,
            createdAt: $createdAt,
            updatedAt: new UpdatedAt(new DateTimeImmutable('2025-10-04 12:45:00')),
        );

        $this->photographRepository->save($photograph2);
        $photographAfterUpdate = $this->photographRepository->findOneByUUID($uuid);

        self::assertSame($updatedTitle, $photographAfterUpdate->title());
        self::assertSame($updatedDescription, $photographAfterUpdate->description());

        self::assertNotSame($photograph1, $photograph2);
        self::assertNotSame($photograph2, $photographAfterUpdate);
        self::assertSame($photograph1, $photographAfterUpdate);

        self::assertSame($photograph2->uuid(), $photographAfterUpdate->uuid());
        self::assertSame($photograph2->title(), $photographAfterUpdate->title());
        self::assertSame($photograph2->description(), $photographAfterUpdate->description());
        self::assertSame($photograph2->filePath(), $photographAfterUpdate->filePath());
        self::assertSame($photograph2->createdAt(), $photographAfterUpdate->createdAt());
        self::assertSame($photograph2->updatedAt(), $photographAfterUpdate->updatedAt());

        self::assertSame($photograph1->uuid(), $photographAfterUpdate->uuid());
        self::assertSame($photograph1->title(), $photographAfterUpdate->title());
        self::assertSame($photograph1->description(), $photographAfterUpdate->description());
        self::assertSame($photograph1->filePath(), $photographAfterUpdate->filePath());
        self::assertSame($photograph1->createdAt(), $photographAfterUpdate->createdAt());
        self::assertSame($photograph1->updatedAt(), $photographAfterUpdate->updatedAt());

        self::assertSame($photograph1->uuid(), $uuid);
        self::assertNotSame($photograph1->title(), $title);
        self::assertNotSame($photograph1->description(), $description);
        self::assertNotSame($photograph1->filePath(), $filePath);
        self::assertSame($photograph1->createdAt(), $createdAt);
        self::assertNotSame($photograph1->updatedAt(), $updatedAt);
    }

    #[Test]
    public function updatesWhenSavingPhotographUsingWithers(): void
    {
        $uuid = new UUID('80f72498-496a-4d73-ae30-6c89267e2cfe');

        $title = new Title('Title');
        $description = new Description('Description');
        $filePath = new FilePath('/public/images/imageA.jpg');
        $createdAt = new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00'));
        $updatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00'));

        $photograph = new Photograph(
            uuid: $uuid,
            title: $title,
            description: $description,
            filePath: $filePath,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );

        $this->photographRepository->save($photograph);
        $photographAfterInsert = $this->photographRepository->findOneByUUID($uuid);

        self::assertInstanceOf(Photograph::class, $photographAfterInsert);
        self::assertSame($photograph, $photographAfterInsert);

        $updatedTitle = new Title('Updated Title from updatesWhenSavingPhotographUsingWithers');
        $updatedDescription = new Description('Updated Description from updatesWhenSavingPhotographUsingWithers');
        $updatedFilePath = new FilePath('/public/images/imageA.jpg');

        $photographBeforeUpdate = $photographAfterInsert
            ->withTitle($updatedTitle)
            ->withDescription($updatedDescription)
            ->withFilePath($updatedFilePath)
        ;

        self::assertNotSame($photograph, $photographBeforeUpdate);
        self::assertNotSame($photographAfterInsert, $photographBeforeUpdate);

        $this->photographRepository->save($photographBeforeUpdate);
        $photographAfterUpdate = $this->photographRepository->findOneByUUID($uuid);

        self::assertNotSame($photographBeforeUpdate, $photographAfterUpdate);
        self::assertSame($photograph, $photographAfterUpdate);
        self::assertNotSame($photograph, $photographBeforeUpdate);

        self::assertSame($photographAfterUpdate->title(), $updatedTitle);
        self::assertSame($photographAfterUpdate->description(), $updatedDescription);
        self::assertSame($photographAfterUpdate->filePath(), $updatedFilePath);
        self::assertSame($photographAfterUpdate->title(), $photographBeforeUpdate->title());
        self::assertSame($photographAfterUpdate->description(), $photographBeforeUpdate->description());

        self::assertSame($photograph->uuid(), $photographAfterUpdate->uuid());
        self::assertSame($photograph->title(), $photographAfterUpdate->title());
        self::assertSame($photograph->description(), $photographAfterUpdate->description());
        self::assertSame($photograph->filePath(), $photographAfterUpdate->filePath());
        self::assertSame($photograph->createdAt(), $photographAfterUpdate->createdAt());
        self::assertSame($photograph->updatedAt(), $photographAfterUpdate->updatedAt());

        self::assertSame($photograph->uuid(), $uuid);
        self::assertNotSame($photograph->title(), $title);
        self::assertNotSame($photograph->description(), $description);
        self::assertNotSame($photograph->filePath(), $filePath);
        self::assertSame($photograph->createdAt(), $createdAt);
        self::assertSame($photograph->updatedAt(), $updatedAt);
    }

    #[Test]
    public function canInsertFindUpdateRemove(): void
    {
        $uuid = new UUID('a641f4a7-45ee-4c1a-9e1f-bb4370ce6537');
        $title = new Title('Title for PhotographRepositoryTest::canSaveFindRemove');
        $description = new Description('Description for PhotographRepositoryTest::canSaveFindRemove');
        $filePath = new FilePath('/public/images/imageA.jpg');
        $createdAt = new CreatedAt(new DateTimeImmutable('2025-10-04 12:20:00'));
        $updatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 12:40:00'));

        $photograph = new Photograph(
            uuid: $uuid,
            title: $title,
            description: $description,
            filePath: $filePath,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );

        $this->photographRepository->save($photograph);
        $photographAfterInsert = $this->photographRepository->findOneByUUID($uuid);

        self::assertInstanceOf(Photograph::class, $photographAfterInsert);
        $this->assertEquals($uuid, $photographAfterInsert->uuid());
        $this->assertEquals($title, $photographAfterInsert->title());
        $this->assertEquals($description, $photographAfterInsert->description());
        $this->assertEquals($filePath, $photographAfterInsert->filePath());
        $this->assertEquals($createdAt, $photographAfterInsert->createdAt());
        $this->assertEquals($updatedAt, $photographAfterInsert->updatedAt());

        $updatedTitle = new Title('Updated Title for PhotographRepositoryTest::canSaveFindRemove');
        $updatedDescription = new Description('Updated Description for PhotographRepositoryTest::canSaveFindRemove');
        $updatedFilePath = new FilePath('/public/images/imageB.jpg');
        $updatedUpdatedAt = new UpdatedAt(new DateTimeImmutable('2025-10-04 16:55:00'));

        $photographBeforeUpdate = $photographAfterInsert
            ->withTitle($updatedTitle)
            ->withDescription($updatedDescription)
            ->withFilePath($updatedFilePath)
            ->withUpdatedAt($updatedUpdatedAt);

        $this->photographRepository->save($photographBeforeUpdate);
        $photographAfterUpdate = $this->photographRepository->findOneByUUID($uuid);

        self::assertInstanceOf(Photograph::class, $photographAfterUpdate);
        $this->assertEquals($updatedTitle, $photographAfterUpdate->title());
        $this->assertEquals($updatedDescription, $photographAfterUpdate->description());
        $this->assertEquals($updatedFilePath, $photographAfterUpdate->filePath());
        $this->assertEquals($updatedUpdatedAt, $photographAfterUpdate->updatedAt());

        $this->photographRepository->remove($photographAfterUpdate);
        $photographAfterRemove = $this->photographRepository->findOneByUUID($uuid);

        $this->assertNull($photographAfterRemove);
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        $em = self::getContainer()->get('doctrine')->getManager();
        $em->getConnection()->close();
        $em->close();
    }

    /**
     * @throws Exception
     */
    private function isUsingSqlite(): bool
    {
        $em = static::getContainer()->get(EntityManagerInterface::class);
        $connection = $em->getConnection();
        $databasePlatform = $connection->getDatabasePlatform();
        return $databasePlatform instanceof SqlitePlatform;
    }

    private function createSqliteSchema(): void
    {
        $em = static::getContainer()->get(EntityManagerInterface::class);
        $metadata = $em->getMetadataFactory()->getAllMetadata();

        $schemaTool = new SchemaTool($em);
        $schemaTool->createSchema($metadata);
    }

    private static function assertHasValidUUID(string $uuid): void
    {
        self::assertMatchesRegularExpression(
            pattern: '/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',
            string: $uuid,
        );
    }
}
